"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['contacts.py']
DATA_FILES = []
OPTIONS = {
    'plist': {
        'NSContactsUsageDescription': 'Ketchup needs access to your contacts to deliver an amazing experience.',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
